/**
 * NuggetNotesService
 * Haiku-powered note generator for real-time lecture notes.
 * Generates 1-3 bullet point notes from transcript chunks.
 * Called every ~45 seconds for efficient, continuous note-taking.
 */

import type { AIClient } from './AIClient.js';
import type { LectureContext } from './LectureContextService.js';

/**
 * A single note generated by Nugget
 */
export interface NuggetNote {
  /** Unique identifier */
  id: string;
  /** Note text content */
  text: string;
  /** Timestamp when note was generated (ms since epoch) */
  timestamp: number;
  /** Recording time in seconds when this note was generated */
  recordingTime: number;
}

/**
 * Configuration for NuggetNotesService
 */
export interface NuggetNotesConfig {
  /** Minimum words before generating notes (default: 30) */
  minWordsForGeneration?: number;
  /** Minimum interval between generations in ms (default: 45000 = 45s) */
  minIntervalMs?: number;
}

const DEFAULT_CONFIG: Required<NuggetNotesConfig> = {
  minWordsForGeneration: 30,
  minIntervalMs: 45000, // 45 seconds
};

/**
 * Service for generating notes from transcript using Haiku 4.5
 */
export class NuggetNotesService {
  private notes: NuggetNote[] = [];
  private lastGenerationTime = 0;
  private pendingWords = 0;
  private config: Required<NuggetNotesConfig>;
  private noteCounter = 0;

  constructor(
    private aiClient: AIClient,
    config?: NuggetNotesConfig
  ) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Get all generated notes
   */
  getNotes(): NuggetNote[] {
    return [...this.notes];
  }

  /**
   * Check if note generation should be triggered
   */
  shouldGenerate(transcriptChunk: string): boolean {
    const wordCount = transcriptChunk.trim().split(/\s+/).filter(w => w.length > 0).length;
    this.pendingWords += wordCount;

    const timeSinceLastGeneration = Date.now() - this.lastGenerationTime;
    const enoughTime = timeSinceLastGeneration >= this.config.minIntervalMs;
    const enoughWords = this.pendingWords >= this.config.minWordsForGeneration;

    return enoughTime && enoughWords;
  }

  /**
   * Generate notes from transcript chunk using Haiku
   * @param transcript Recent transcript text (~100 words)
   * @param context Current lecture context from Sonnet
   * @param recordingTimeSeconds Current recording time in seconds
   * @returns Array of new notes generated
   */
  async generateNotes(
    transcript: string,
    context: LectureContext,
    recordingTimeSeconds: number
  ): Promise<NuggetNote[]> {
    try {
      const prompt = this.buildPrompt(transcript, context);
      
      let response = '';
      await this.aiClient.chatStream(
        prompt,
        [],
        {
          maxTokens: 100,
          temperature: 0.2,
          model: 'claude-haiku-4-5-20251001'
        },
        (chunk) => { response += chunk; }
      );

      const newNotes = this.parseNotes(response, recordingTimeSeconds);
      
      if (newNotes.length > 0) {
        this.notes.push(...newNotes);
        this.lastGenerationTime = Date.now();
        this.pendingWords = 0;
        console.log(`📝 Generated ${newNotes.length} notes at ${Math.floor(recordingTimeSeconds / 60)}:${String(Math.floor(recordingTimeSeconds % 60)).padStart(2, '0')}`);
      }

      return newNotes;
    } catch (error) {
      // Graceful degradation: log error but don't throw
      console.warn('⚠️ NuggetNotesService generation failed:', error);
      return [];
    }
  }

  /**
   * Build the prompt for Haiku note generation
   */
  private buildPrompt(transcript: string, context: LectureContext): string {
    const contextStr = context.currentTopic 
      ? `Topic: "${context.currentTopic}". Themes: ${context.themes.join(', ') || 'general'}.`
      : 'Lecture in progress.';

    return `Create 1-3 concise bullet notes from this lecture segment.

CONTEXT: ${contextStr}

TRANSCRIPT:
"${transcript.slice(-500)}"

Output ONLY bullet points (no intro, no explanation). Each must start with "- ":`;
  }

  /**
   * Parse Haiku's response into NuggetNote objects
   */
  private parseNotes(response: string, recordingTimeSeconds: number): NuggetNote[] {
    const lines = response
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.startsWith('-') || line.startsWith('•'));

    const now = Date.now();
    
    return lines
      .slice(0, 3) // Max 3 notes per generation
      .map(line => {
        // Remove bullet point prefix and clean up
        const text = line
          .replace(/^[-•]\s*/, '')
          .replace(/\*\*/g, '') // Remove markdown bold
          .trim();
        
        if (text.length < 5) return null; // Skip very short notes
        
        this.noteCounter++;
        return {
          id: `note-${now}-${this.noteCounter}`,
          text,
          timestamp: now,
          recordingTime: recordingTimeSeconds,
        };
      })
      .filter((note): note is NuggetNote => note !== null);
  }

  /**
   * Reset service for new session
   */
  clearNotes(): void {
    this.notes = [];
    this.lastGenerationTime = 0;
    this.pendingWords = 0;
    this.noteCounter = 0;
    console.log('🔄 NuggetNotesService cleared');
  }
}
